In [67]:
import pandas as pd

In [68]:
df = pd.read_csv("bangalore_startups_details.csv")

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       1085 non-null   object
 1   sector     1084 non-null   object
 2   founded    742 non-null    object
 3   team_size  687 non-null    object
 4   url        1085 non-null   object
dtypes: object(5)
memory usage: 42.5+ KB

In [70]:
df["sector"].unique

<bound method Series.unique of 0                                                  edtech
1                                                deeptech
2       s saas deeptech fintech ai consumer healthtech...
3                                                      3.
4                 datacenter) other unspecified ♡ apply ↗
                              ...
1080                                                  d2c
1081    s saas deeptech fintech ai consumer healthtech...
1082                                                   ai
1083                                           healthtech
1084                                              fintech
Name: sector, Length: 1085, dtype: object>

In [71]:
df.head()

,name,sector,founded,team_size,url
0,AARUM,edtech,NaN,NaN,https://www.bangalorestartupmap.com/company/aarum
1,ABB India,deeptech,NaN,500+,https://www.bangalorestartupmap.com/company/ab...
2,Accel India,s saas deeptech fintech ai consumer healthtech...,NaN,NaN,https://www.bangalorestartupmap.com/company/ac...
3,Acceldata,3.,2018,201-500,https://www.bangalorestartupmap.com/company/ac...
4,Accenture India,datacenter) other unspecified ♡ apply ↗,NaN,500+,https://www.bangalorestartupmap.com/company/ac...

In [72]:
df = df.drop(columns=["url","sector"])

In [73]:
import pandas as pd

# Example:
# df['col'] has mixed numbers and strings/objects

# 1. Convert to numeric, forcing errors to NaN
df['founded'] = pd.to_numeric(df['founded'], errors='coerce')

# 2. Replace NaN (the original object/non-numeric values) with 0
df['founded'] = df['founded'].fillna(0)

# Optional: if you want it as integer
df['founded'] = df['founded'].astype(int)

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       1085 non-null   object
 1   founded    1085 non-null   int64
 2   team_size  687 non-null    object
dtypes: int64(1), object(2)
memory usage: 25.6+ KB

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       1085 non-null   object
 1   founded    1085 non-null   int64
 2   team_size  687 non-null    object
dtypes: int64(1), object(2)
memory usage: 25.6+ KB

In [76]:
# Convert the founded column to numbers
df["founded"] = pd.to_numeric(df["founded"], errors="coerce")

# Keep only companies founded after 2022
companies_after_2022 = df[df["founded"] > 2022]

# Display the result
companies_after_2022

                       name  founded team_size
14    Aetos Innovation Labs     2025      1-10
32               Alt Carbon     2023     11-50
49                 AntiNorm     2024      1-10
101                   Basil     2023     11-50
104                  Belong     2023     11-50
...                     ...      ...       ...
959                 Trupeer     2024     11-50
983     Vaani Research Labs     2023     11-50
1002                  Vobiz     2025      1-10
1009                  Vutto     2024    51-200
1030                  Wippi     2024      1-10

[70 rows x 3 columns]

In [77]:
companies_after_2022.to_csv("final_list_startups.csv", index=False)

In [86]:
companies_after_2022["team_size"].unique()

['cat 1', 'cat 2', 'cat 3', NaN]
Categories (4, object): [0 < 'cat 1' < 'cat 2' < 'cat 3']

In [87]:
companies_after_2022["team_size"] = companies_after_2022["team_size"].fillna(0)

In [88]:
companies_after_2022["team_size"].unique()

['cat 1', 'cat 2', 'cat 3', 0]
Categories (4, object): [0 < 'cat 1' < 'cat 2' < 'cat 3']

In [80]:
companies_after_2022["team_size"] = companies_after_2022["team_size"].map({"1-10" :"cat 1","11-50":"cat 2","51-200":"cat 3"})

C:\Users\Mohammed Hyder\AppData\Local\Temp\ipykernel_19848\3327041873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  companies_after_2022["team_size"] = companies_after_2022["team_size"].map({"1-10" :"cat 1","11-50":"cat 2","51-200":"cat 3"})

In [81]:
companies_after_2022

                       name  founded team_size
14    Aetos Innovation Labs     2025     cat 1
32               Alt Carbon     2023     cat 2
49                 AntiNorm     2024     cat 1
101                   Basil     2023     cat 2
104                  Belong     2023     cat 2
...                     ...      ...       ...
959                 Trupeer     2024     cat 2
983     Vaani Research Labs     2023     cat 2
1002                  Vobiz     2025     cat 1
1009                  Vutto     2024     cat 3
1030                  Wippi     2024     cat 1

[70 rows x 3 columns]

In [82]:
# Suppose your DataFrame is df and the column is 'team_size'
order = [0, "cat 1", "cat 2", "cat 3"]

companies_after_2022["team_size"] = pd.Categorical(companies_after_2022["team_size"], categories=order, ordered=True)
companies_after_2022 = companies_after_2022.sort_values("team_size")

C:\Users\Mohammed Hyder\AppData\Local\Temp\ipykernel_19848\600941678.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  companies_after_2022["team_size"] = pd.Categorical(companies_after_2022["team_size"], categories=order, ordered=True)

In [83]:
companies_after_2022["team_size"].unique()

['cat 1', 'cat 2', 'cat 3', NaN]
Categories (4, object): [0 < 'cat 1' < 'cat 2' < 'cat 3']

In [84]:
companies_after_2022.to_csv("final_list_startups.csv", index=False)